title: 'impulsetechnologies.campaignr::lang.plugin.events'
modelClass: ImpulseTechnologies\Campaignr\Models\Event
list: $/impulsetechnologies/campaignr/models/event/columns.yaml
recordUrl: 'impulsetechnologies/campaignr/events/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
