name: Events
modelClass: ImpulseTechnologies\Campaignr\Models\Event
form: $/impulsetechnologies/campaignr/models/event/fields.yaml
defaultRedirect: impulsetechnologies/campaignr/events
create:
    redirect: 'impulsetechnologies/campaignr/events/update/:id'
    redirectClose: impulsetechnologies/campaignr/events
update:
    redirect: impulsetechnologies/campaignr/events
    redirectClose: impulsetechnologies/campaignr/events
